### PR TITLE
Begin Chart Storage

### PR DESCRIPTION
**Pull request by ShimElliott**
Added a unit test for the saveChart function in chartStorage. Also added JSDOM Jest and regular Jest.

### CODE REVIEW

**Comment by ShimElliott** [comment]
Finished chartStorage unit tests, this merge covers all of the commits, not just the ones from the first comment.

**Comment by ShimElliott** [comment]
Please don't merge this yet, it needs to be updated. Merging right now will break things!

**Comment by ShimElliott** [comment]
Now the branch is up to date and can be merged safely :)

**Review by dualsm — APPROVED** [review]
Passed the tests, looks like good jest to me

**Pull request merged**
